import type { StyleTemplate } from './types'

export const STYLE_TEMPLATES: StyleTemplate[] = [
  {
    id: 'enchanted-watercolor',
    name: 'Enchanted Watercolor',
    description: 'Soft, dreamy watercolors with forest greens — perfect for fairy tales and gentle stories',
    imagePath: '/gallery/watercolor-enchanted-oak.webp',
    blurDataURL: 'data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAABQBACdASoUABQAPzmUwFmvKiajqAgB4CcJQBhQAiOjOwyycPjblzX6yDaoAPlRPH43MivCa0yZVdT5Uy/YBJAnzQpLnHBmuF4/OdKWJu6PXjd85dqMFhf2GoOwKzrXk867uDL6BssIUcfCyBka6ln32IbLrrMrSk152X2pggEPJj398AA=',
    tags: ['whimsical', 'warm', 'classic'],
    stylePreset: 'watercolor',
    palettePreset: 'forest',
    moods: ['whimsical', 'peaceful'],
    characterStyle: 'classic-storybook',
    illustrationType: 'full-page',
    era: 'timeless',
    culturalInfluence: 'european',
    detailLevel: 'moderate',
  },
  {
    id: 'epic-oil-painting',
    name: 'Epic Oil Painting',
    description: 'Rich, dramatic oil paintings with sunset tones — ideal for fantasy and adventure',
    imagePath: '/gallery/oil-painting-knight-kingdom.webp',
    blurDataURL: 'data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAABQBACdASoUABQAPzmMulYvKSWkqA1R4CcJYgCxHtpBo+3zC9UHIxlFH/sAAPI8nMLS1Ne0SmH2PvtNqUF24LWD08O0xvI6jKJkb8N6RbUpDpozWj7aoPssNDts0VRtOpaU4aDnHjrzSqIZW5+AAA==',
    tags: ['dramatic', 'warm', 'classic'],
    stylePreset: 'oil-painting',
    palettePreset: 'sunset',
    moods: ['adventurous', 'dramatic'],
    characterStyle: 'realistic',
    illustrationType: 'full-page',
    era: 'medieval',
    culturalInfluence: 'european',
    detailLevel: 'rich',
  },
  {
    id: 'moonlit-manga',
    name: 'Moonlit Manga',
    description: 'Expressive anime-inspired art with nighttime hues — great for young adult and fantasy',
    imagePath: '/gallery/manga-sorceress-library.webp',
    blurDataURL: 'data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAABQBACdASoUABQAPzmOuFavKaUjqA1R4CcJZQDDNA3vpAGNNc1Gxbct9EkAAP5JQolHLyRxw4N03kIvFMPZAuFOL6vSxZCp2eRwW+Lf/R4LxaWyUnyCFsp+S0/JFb1agO9jC+ZmH+TgbpjUOcNwVk4JRs/gAAAA',
    tags: ['dramatic', 'cool', 'modern'],
    stylePreset: 'manga-anime',
    palettePreset: 'night',
    moods: ['mysterious', 'dramatic'],
    characterStyle: 'stylized-cartoon',
    illustrationType: 'full-page',
    era: 'timeless',
    culturalInfluence: 'east-asian',
    detailLevel: 'rich',
  },
  {
    id: 'playful-vector',
    name: 'Playful Vector',
    description: 'Clean, bold shapes with soft pastels — ideal for children\'s picture books',
    imagePath: '/gallery/flat-vector-fox-picnic.webp',
    blurDataURL: 'data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAACQBACdASoUABQAPzmQvFgvKaWjqAqp4CcJagDImA9o7//2NgiLgZhjuE84YAAA/pNUIYI81NAzB5uH30uRMTu1HmN//OMJBiHxQPQvLzTJYwFFlVNAxxBuJYyr04l0ullHzGOtnR91iVhFlIJW46iAAAA=',
    tags: ['playful', 'minimal', 'modern'],
    stylePreset: 'flat-vector',
    palettePreset: 'pastel',
    moods: ['cheerful', 'whimsical'],
    characterStyle: 'stylized-cartoon',
    illustrationType: 'full-page',
    era: 'timeless',
    culturalInfluence: 'none',
    detailLevel: 'simple',
  },
  {
    id: 'cozy-pencil-sketch',
    name: 'Cozy Pencil Sketch',
    description: 'Detailed graphite drawings with warm earthy tones — timeless literary feel',
    imagePath: '/gallery/pencil-sketch-fireplace.webp',
    blurDataURL: 'data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAACwBACdASoUABQAPzmUwVmvKicjqAgB4CcJYgCsMy/BfDokdYUEo9Q22IsshnoAAP6sQNRaonONxV0x6l+haPCDX6It2+zmnHGVHDsWEv5KZIkW6MeEgQZPLNAL4aCDPhHkP+QTdXMAC6WAAsnYsb7DUWFq9nsgf10gAWyYAAA=',
    tags: ['warm', 'classic', 'minimal'],
    stylePreset: 'pencil-sketch',
    palettePreset: 'warm-earthy',
    moods: ['peaceful', 'melancholic'],
    characterStyle: 'realistic',
    illustrationType: 'vignette',
    era: 'victorian',
    culturalInfluence: 'european',
    detailLevel: 'moderate',
  },
  {
    id: 'whimsical-storybook',
    name: 'Whimsical Storybook',
    description: 'Warm, charming illustrations with ocean blues — classic children\'s adventure feel',
    imagePath: '/gallery/storybook-mouse-captain.webp',
    blurDataURL: 'data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAACQBACdASoUABQAPzmSv1mvKaajqAgB4CcJQBYhiYgw8gTmLd7fz1vvyu1Y6EAA/lkJiyTB2SIhV1NMygP3ovBk3BRGGRoMRQT9G5m59Imhy0zvD5Cm7Ji1s8+9T1RVrdNyZfLYI98UKGepiwGVEa3yrfyLvxrC03dPnPaI4wptevQmbU7r4nsI4wr7E+r2AAA=',
    tags: ['whimsical', 'playful', 'warm'],
    stylePreset: 'storybook',
    palettePreset: 'ocean',
    moods: ['cheerful', 'adventurous'],
    characterStyle: 'anthropomorphic',
    illustrationType: 'full-page',
    era: 'timeless',
    culturalInfluence: 'none',
    detailLevel: 'moderate',
  },
  {
    id: 'polished-digital',
    name: 'Polished Digital',
    description: 'Smooth, professional digital art with cool blues — atmospheric and refined',
    imagePath: '/gallery/digital-painting-victorian.webp',
    blurDataURL: 'data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAADwBACdASoUABQAPzmUwVmvKicjqAgB4CcJQBZwAS2CoFf6YIGsCuU3qrhK+fULxAAA/oGMe1DdNw72yUifc5Xy2+WT62CxZiDixH4wdU1h5phZ8bFv7LtgY2E3Yd0HxctintbwxNWHz3sctGCUaoK6NlwCUK7b7Q0UtLkxkd29eU4MMoHqyGT2IYtLpL+591/EDBUUAAA=',
    tags: ['cool', 'modern', 'dramatic'],
    stylePreset: 'digital-painting',
    palettePreset: 'cool-blues',
    moods: ['mysterious', 'dramatic'],
    characterStyle: 'realistic',
    illustrationType: 'full-page',
    era: 'victorian',
    culturalInfluence: 'european',
    detailLevel: 'rich',
  },
  {
    id: 'nostalgic-retro',
    name: 'Nostalgic Retro',
    description: 'Mid-century vintage style with autumn warmth — perfect for nostalgic adventures',
    imagePath: '/gallery/retro-vintage-attic.webp',
    blurDataURL: 'data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAABwBACdASoUABQAPzmUwlmvKicjqAgB4CcJQBg5giN4uHH7UQyBxxtO/oo2gAD9pBbgRJTIsI9/6A9MJuLCKYLldtgbGKOOHGKvAnJkAYHuzEYa3R2PcFFVdO08h0fwtxGxv/t6MK0XqOO/GUzvjWG7t5KG/EIpSX2pgCJNiHJaQQ1Apkt7ioPED/lnIKUAAAA=',
    tags: ['warm', 'classic', 'playful'],
    stylePreset: 'retro-vintage',
    palettePreset: 'autumn',
    moods: ['adventurous', 'humorous'],
    characterStyle: 'stylized-cartoon',
    illustrationType: 'full-page',
    era: 'early-20th',
    culturalInfluence: 'none',
    detailLevel: 'moderate',
  },
  {
    id: 'elegant-line-art',
    name: 'Elegant Line Art',
    description: 'Precise ink contours in monochrome — refined and meditative',
    imagePath: '/gallery/line-art-heron-lotus.webp',
    blurDataURL: 'data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAwBACdASoUABQAPzmSv1mvKaajqAgB4CcJaQAALlRds+4z77hxaK3IgAAA/ucTsXwEtuthVRejV7qlQzu0Lv1flVa/PpBU50z6oqX7ZYjX5CR2ioboA+pSilUSdjegAAA=',
    tags: ['minimal', 'cool', 'classic'],
    stylePreset: 'line-art',
    palettePreset: 'monochrome',
    moods: ['peaceful', 'melancholic'],
    characterStyle: 'abstract-silhouette',
    illustrationType: 'vignette',
    era: 'timeless',
    culturalInfluence: 'east-asian',
    detailLevel: 'moderate',
  },
  {
    id: 'vibrant-collage',
    name: 'Vibrant Collage',
    description: 'Mixed media textures with bold, saturated colors — eclectic and cultural',
    imagePath: '/gallery/collage-moroccan-medina.webp',
    blurDataURL: 'data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAABwBACdASoUABQAPzmUwFmvKiajqAgB4CcJYwCCSQRWrS8YtV1o15HfN4sFOAD+s6Y2r2R057MEOGAyAkrkhHMtFn6zBd/023qdNIasGL184+tqbfy8Zx7iQZUCvw+qOxp94xfqwEjuGbbN1fecLQcqm7wUFyvR2F7NQQGeLREPWbufpeVQfJhrgngAAA==',
    tags: ['vibrant', 'warm', 'modern'],
    stylePreset: 'collage',
    palettePreset: 'vibrant',
    moods: ['cheerful', 'adventurous'],
    characterStyle: 'stylized-cartoon',
    illustrationType: 'full-page',
    era: 'modern',
    culturalInfluence: 'middle-eastern',
    detailLevel: 'rich',
  },
]

const STYLE_TEMPLATE_MAP: Record<string, StyleTemplate> =
  Object.fromEntries(STYLE_TEMPLATES.map(t => [t.id, t]))

export function getStyleTemplate(id: string): StyleTemplate | undefined {
  return STYLE_TEMPLATE_MAP[id]
}
